---
- name: Permission present example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure permission TestPerm1 is present
    ipapermission:
      ipaadmin_password: SomeADMINpassword
      name: TestPerm1
      object_type: host
      right: all
